// [1, 2, 3][Symbol.iterator]() needs to return an iterator
// that enumerates the items according to the es6 iterator protocol;
// otherwise the code generated by babel won't work
Object.defineProperty(Array.prototype, Symbol.iterator, {
    enumerable: false,
    value: function <T>() {
        const items: T[] = this;
        let index = 0;

        return {
            next() {
                const i = index++;

                return {
                    done: i >= items.length,
                    value: items[i]
                };
            }
        };
    }
});
