#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

#"$basedir/../node_modules/.bin/tsc" "$@"

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../esc"
  ret=$?
else 
  node  "$basedir/../esc"
  ret=$?
fi
exit $ret
